# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20170131_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('product owner', 'Product Owner'), ('scrum master', 'Scrum Master'), ('project master', 'Project Master')], max_length=255, verbose_name='Role'),
        ),
    ]
