# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20170207_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuelog',
            name='labor_costs',
        ),
        migrations.AddField(
            model_name='issuelog',
            name='cost',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
