# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_merge_20170205_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='pm_role_access',
            field=models.BooleanField(default=False, verbose_name='PM role access'),
        ),
    ]
