# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20170208_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuelog',
            name='labor_costs',
        ),
        migrations.AddField(
            model_name='issuelog',
            name='cost',
            field=models.PositiveIntegerField(default=1, verbose_name='Cost'),
            preserve_default=False,
        ),
    ]
