# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20170218_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuelog',
            options={'ordering': ['-date_created']},
        ),
    ]
