# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20170209_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
