# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20170209_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelog',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cost'),
        ),
    ]
