# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20170209_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
