# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_merge_20170219_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='relies_link',
            new_name='release_link',
        ),
    ]
