# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170301_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimation_link',
            field=models.CharField(default=project.models.generate_estimation_link, max_length=1000, verbose_name='Estimation'),
        ),
    ]
