# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_estimation_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='estimation',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(240)], verbose_name='Estimation'),
        ),
    ]
