# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='feedback_text',
            field=models.TextField(blank=True, null=True, verbose_name='Retrospective text'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='relies_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
