# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='estimation',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(240)], verbose_name='Estimation'),
            preserve_default=False,
        ),
    ]
