# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170207_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Note text')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('User_story', 'User_story'), ('Task', 'Task'), ('Bug', 'Bug')], default='Task', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=255, verbose_name='Status'),
        ),
    ]
