# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170201_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
