# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_sprint_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.PositiveIntegerField(choices=[(-1, 'High'), (-2, 'Medium'), (-3, 'Low')], default=0, verbose_name='Priority'),
        ),
    ]
