# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170210_0906'),
        ('project', '0003_auto_20170210_1806'),
    ]

    operations = [
    ]
