# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170209_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
    ]
