# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_issuecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
