# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('User_story', 'User_story'), ('Task', 'Task'), ('Bug', 'Bug')], default='Task', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='duration',
            field=models.PositiveIntegerField(default=10, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='feedback_text',
            field=models.TextField(blank=True, null=True, verbose_name='Retrospective text'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='relies_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
    ]
