# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170203_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
    ]
