# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170214_2306'),
        ('project', '0002_auto_20170215_1051'),
    ]

    operations = [
    ]
