# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_issue_order'),
        ('project', '0006_auto_20170203_2017'),
    ]

    operations = [
    ]
