# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170218_1750'),
        ('project', '0007_auto_20170218_2217'),
    ]

    operations = [
    ]
