# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_merge_20170204_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecomment',
            options={'ordering': ['-date_created']},
        ),
    ]
