# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_merge_20170204_2014'),
        ('project', '0008_auto_20170205_1422'),
    ]

    operations = [
    ]
