# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170220_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='feedback_text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Sprint review'),
        ),
    ]
