# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170226_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('User_story', 'User story'), ('Task', 'Task'), ('Bug', 'Bug')], default='User_story', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Duration in days'),
        ),
    ]
