# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170226_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Duration in days'),
        ),
    ]
