# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20170126_1754'),
        ('workflow', '0005_project_is_active'),
    ]

    operations = [
    ]
